# Uncomment the next line to define a global platform for your project
platform :ios, '13.6'

target 'IOS-Investment-App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'CoinpaprikaAPI'
  pod 'lottie-ios', '~> 3.1.8'
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'alamofire5'
  pod 'Charts'
  # Pods for IOS-Investment-App

end
