//
//  BuyCoinsWireframe.swift
//  IOS-Investment-App
//
//  Created by enki corbin on 19/12/2020.
//  Copyright (c) 2020 enki corbin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class BuyCoinsWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -
    let moduleViewController = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(identifier: "BuyCoin") as! BuyCoinsViewController

    init(coinId: String) {
        let interactor = BuyCoinsInteractor()
        super.init(viewController: moduleViewController)

        let presenter = BuyCoinsPresenter(view: moduleViewController, wireframe: self, interactor: interactor, coinId: coinId)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension BuyCoinsWireframe: BuyCoinsWireframeInterface {
}
