//
//  BuyCoinsInterfaces.swift
//  IOS-Investment-App
//
//  Created by enki corbin on 19/12/2020.
//  Copyright (c) 2020 enki corbin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Coinpaprika

protocol BuyCoinsWireframeInterface: WireframeInterface {
}

protocol BuyCoinsViewInterface: ViewInterface {
    
    func updateCoinView(coinInfos: Ticker)
    func updateCoinView(coinOhlcv: [Ohlcv])
    
    func didBoughtCoin(success: Bool)

}

protocol BuyCoinsPresenterInterface: PresenterInterface {
    //Input
    func getCoinInfos()
    func getCoinOhlcv(from date: Date)
    func buyCoin(usdAmount: String?)

    //Output
    func didGetCoinInfos(coinInfos: CoinStocksEntity)
    func didGetCoinOhlcv(coinInfos: CoinStocksEntity)
    func didBuyCoin(success: Bool)
}

protocol BuyCoinsInteractorInterface: PresenterInterface {
    func getCoinInfosFromApi(for coinId: String, storeCoin: @escaping (CoinStocksEntity) -> Void)
    func getCoinOhlcvFromApi(for coinId: String, from date: Date, storeCoinOhlvc: @escaping (CoinStocksEntity) -> Void)
    func getConvertionRateFromApi(for coinId: String, usdAmount: Int, convertionCallBack: @escaping (String, Int, Float) -> Void)
    func buyCoin(coinId: String, coinAmount: Float, usdAmount: Int) -> Bool
}
