//
//  BuyCoinsPresenter.swift
//  IOS-Investment-App
//
//  Created by enki corbin on 19/12/2020.
//  Copyright (c) 2020 enki corbin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class BuyCoinsPresenter {

    // MARK: - Private properties -

    private unowned let view: BuyCoinsViewInterface
    private let wireframe: BuyCoinsWireframeInterface
    private let interactor: BuyCoinsInteractorInterface

    private let coinId: String
    // MARK: - Lifecycle -

    init(view: BuyCoinsViewInterface, wireframe: BuyCoinsWireframeInterface, interactor: BuyCoinsInteractorInterface, coinId: String) {
        self.view = view
        self.wireframe = wireframe
        self.interactor = interactor
        
        self.coinId = coinId
    }
    
    func didGetCoinRate(coinId: String, usdAmount: Int, convertionRate: Float) {
        let coinAmount = Float(usdAmount) * convertionRate
        
        let state = interactor.buyCoin(coinId: coinId, coinAmount: coinAmount, usdAmount: usdAmount)
        didBuyCoin(success: state)
    }
}

// MARK: - Extensions -

extension BuyCoinsPresenter: BuyCoinsPresenterInterface {
    
    func buyCoin(usdAmount: String?) {
        if usdAmount != nil && usdAmount != "" && Int(usdAmount!) != nil {
            interactor.getConvertionRateFromApi(for: coinId, usdAmount: Int(usdAmount!)!, convertionCallBack: didGetCoinRate)
        } else {
            didBuyCoin(success: false)
        }
    }
    
    func didBuyCoin(success: Bool) {
        view.didBoughtCoin(success: success)
    }
 
    func getCoinInfos() {
        interactor.getCoinInfosFromApi(for: coinId, storeCoin: didGetCoinInfos(coinInfos:))
    }
    
    func didGetCoinInfos(coinInfos: CoinStocksEntity) {
        view.updateCoinView(coinInfos: coinInfos.ticker!)
    }
    
    func getCoinOhlcv(from date: Date) {
        
        interactor.getCoinOhlcvFromApi(for: coinId, from: date, storeCoinOhlvc: didGetCoinOhlcv(coinInfos:))
    }
    
    func didGetCoinOhlcv(coinInfos: CoinStocksEntity) {
        view.updateCoinView(coinOhlcv: coinInfos.ohlcv!)
    }
}
