//
//  MarketsViewController.swift
//  IOS-Investment-App
//
//  Created by enki corbin on 01/12/2020.
//  Copyright (c) 2020 enki corbin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MarketsViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: MarketsPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        
        presenter.didLoad()
    }

}

// MARK: - Extensions -

extension MarketsViewController: MarketsViewInterface {
}
