//
//  MarketsPresenter.swift
//  IOS-Investment-App
//
//  Created by enki corbin on 01/12/2020.
//  Copyright (c) 2020 enki corbin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MarketsPresenter {

    // MARK: - Private properties -

    private unowned let view: MarketsViewInterface
    private let interactor: MarketsInteractorInterface
    private let wireframe: MarketsWireframeInterface

    // MARK: - Lifecycle -

    init(view: MarketsViewInterface, interactor: MarketsInteractorInterface, wireframe: MarketsWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension MarketsPresenter: MarketsPresenterInterface {
    
    public func didLoad() {
        interactor.fetchCryptos()
    }
    
}
