//
//  MarketsInterfaces.swift
//  IOS-Investment-App
//
//  Created by enki corbin on 01/12/2020.
//  Copyright (c) 2020 enki corbin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol MarketsWireframeInterface: WireframeInterface {
}

protocol MarketsViewInterface: ViewInterface {
}

protocol MarketsPresenterInterface: PresenterInterface {
    
    func didLoad()
    
}

protocol MarketsInteractorInterface: InteractorInterface {
    
    func fetchCryptos()
    
}

protocol MarketsInteractorOutputInterface: InteractorInterface {
    
    func didFetchCryptos(cryptos: [CryptoEntity])
    
}

