//
//  MarketsInteractor.swift
//  IOS-Investment-App
//
//  Created by enki corbin on 01/12/2020.
//  Copyright (c) 2020 enki corbin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import CryptoCurrencyKit

final class MarketsInteractor {
}

// MARK: - Extensions -

extension MarketsInteractor: MarketsInteractorInterface {
    
    func fetchCryptos() {
            CryptoCurrencyKit.fetchGlobal(convert: .hkd) { r in
            switch r {
            case .success(let global):
                print(global)
//                didFetchCryptos(cryptos: g)
            case .failure(let error):
                print(error)
            }
        }
    }
    
}

extension MarketsInteractor: MarketsInteractorOutputInterface {
    
    func didFetchCryptos(cryptos: [CryptoEntity]) {
        
    }
    
}
