//
//  MarketsInterfaces.swift
//  IOS-Investment-App
//
//  Created by enki corbin on 01/12/2020.
//  Copyright (c) 2020 enki corbin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum MarketsNavigationOption {
    
    case buyCoins
    case sellCoins
    
}

protocol MarketsWireframeInterface: WireframeInterface {
    
    func navigate(to option: MarketsNavigationOption, coinId: String)
    
}

protocol MarketsViewInterface: ViewInterface {
    
    func updateCoins(coins: [CoinEntity])
    func updateBoughtCoins(coins: [CoinBoughtEntity])
    
}

protocol MarketsPresenterInterface: PresenterInterface {
    // Input
    func fetchBoughtCoins()
    func fetchCryptos()
    func didTapBuyCoin(withIdentifier id: String)
    func didTapSellCoin(withIdentifier id: String)
    func getCryptoIcon(coinSymbol: String) -> UIImage?

    //Output
    func didFetchBoughtCoins(coins: [CoinBoughtEntity])
    func didfetchCryptos(_ coins: [CoinEntity])
}

protocol MarketsInteractorInterface: InteractorInterface {
    
    func getCryptoIcon(coinSymbol: String) -> UIImage?
    func fetchBoughtCoins(storeCoins: @escaping (_ coins: [CoinBoughtEntity]) -> Void)
    func fetchCryptos(storeCoins: @escaping (_ coins: [CoinEntity]) -> Void, maxRange: Int)
    
}

