//
//  MarketsWireframe.swift
//  IOS-Investment-App
//
//  Created by enki corbin on 01/12/2020.
//  Copyright (c) 2020 enki corbin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MarketsWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -
    let moduleViewController = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(identifier: "Markets") as! MarketsViewController

    init() {
        super.init(viewController: moduleViewController)

        let interactor = MarketsInteractor()
        let presenter = MarketsPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension MarketsWireframe: MarketsWireframeInterface {
    
    func navigate(to option: MarketsNavigationOption, coinId: String) {
        
        switch option {
        case .buyCoins:
            openBuyCoins(coinId: coinId)
            break
        case .sellCoins:
            openSellCoins(coinId: coinId)
            break
        }
                
    }
    
    private func openBuyCoins(coinId: String) {
        navigationController?.pushWireframe(BuyCoinsWireframe(coinId: coinId))
    }

    private func openSellCoins(coinId: String) {
        navigationController?.pushWireframe(SellCoinsWireframe(coinId: coinId))
    }
    
}
