//
//  BuyCoinsViewController.swift
//  IOS-Investment-App
//
//  Created by enki corbin on 19/12/2020.
//  Copyright (c) 2020 enki corbin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Coinpaprika
import Charts

final class BuyCoinsViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: BuyCoinsPresenterInterface!

    @IBOutlet weak var coinPriceTitleLabel: DesignableLabel!
    @IBOutlet weak var coinPriceValueLabel: UILabel!
    @IBOutlet weak var dateTimeStockValueSegment: DateSegmentControl!
    
    @IBOutlet weak var buyAmountTextField: UITextField!
    @IBOutlet weak var buyButton: DesignableButton!
    @IBOutlet weak var chartViewContainer: DesignableView!
    
    weak var axisFormatDelegate: IAxisValueFormatter?
    var chartView: CandleChart!
    
    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        
        presenter.getCoinInfos()
        let ohlcvFromDate = dateTimeStockValueSegment.getSelectedDate()
        presenter.getCoinOhlcv(from: ohlcvFromDate)
        
        dateTimeStockValueSegment.addTarget(self, action: #selector(BuyCoinsViewController.segmentedControlValueChanged(_:)), for: .valueChanged)
        
        initChartView()
        initBuyAmountPad()
        
    }
    
    func initBuyAmountPad() {
        let toolbar: UIToolbar = UIToolbar()
        
        toolbar.frame = CGRect(x: 0, y: 0, width: view.bounds.width, height: 44)
        toolbar.isTranslucent = false
        toolbar.barTintColor = .gray
        toolbar.tintColor = .white
        toolbar.items = [
            UIBarButtonItem(title: Bundle.main.localizedString(forKey: "done", value: "Done", table: "Localizable"), style: .done, target: self, action: #selector(doneButtonTappedForMyNumericTextField))
        ]
        toolbar.isTranslucent = true
        buyAmountTextField.autoresizingMask = .flexibleHeight
        buyAmountTextField.inputAccessoryView = toolbar
    }
    
    @objc func doneButtonTappedForMyNumericTextField() {
        buyAmountTextField.resignFirstResponder()
    }
    
    func initChartView() {
        let frame = CGRect(x: 10, y: 60, width: chartViewContainer.frame.width - 30, height: chartViewContainer.frame.height - 70)

        chartView = CandleChart(frame: frame)
        chartViewContainer.addSubview(chartView)

        axisFormatDelegate = chartView
    }
    
    @objc func segmentedControlValueChanged(_ sender: UISegmentedControl) {
        
        let ohlcvFromDate = dateTimeStockValueSegment.getSelectedDate()
        presenter.getCoinOhlcv(from: ohlcvFromDate)

        switch dateTimeStockValueSegment.selectedSegmentIndex {
        case 0:
            chartView.selectedDate = .minute
        case 1:
            chartView.selectedDate = .hour
        case 2:
            chartView.selectedDate = .day
        case 3:
            chartView.selectedDate = .month
        case 4:
            chartView.selectedDate = .all
        default:
            chartView.selectedDate = .all
        }
            
    }
    
    @IBAction func BuyClick(_ sender: Any) {
        presenter.buyCoin(usdAmount: buyAmountTextField.text)
    }
    
}

// MARK: - Extensions -

extension BuyCoinsViewController: BuyCoinsViewInterface {
    
    func didBoughtCoin(success: Bool) {
        if success {
            Toast.show(message: "Transaction done", controller: self, type: "success", toastDuration: 2)
        } else {
            Toast.show(message: "An error occured", controller: self, type: "danger", toastDuration: 2)
        }
    }

    func updateCoinView(coinInfos: Ticker) {
        let floatPrice = Float(truncating: coinInfos[.usd].price as NSNumber)

        coinPriceTitleLabel.text = Bundle.main.localizedString(forKey: "priceOf", value: "Price of", table: "Localizable") + " " + coinInfos.name
        coinPriceValueLabel.text = String.formatToDollar(price: floatPrice)
    }
    
    func updateCoinView(coinOhlcv: [Ohlcv]) {
        chartView.updateDataView(coinOhlcv: coinOhlcv, axisFormatDelegate: axisFormatDelegate!)
    }
    
}

