//
//  BuyCoinsViewController.swift
//  IOS-Investment-App
//
//  Created by enki corbin on 19/12/2020.
//  Copyright (c) 2020 enki corbin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Coinpaprika
import Charts

final class BuyCoinsViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: BuyCoinsPresenterInterface!

    @IBOutlet weak var coinPriceTitleLabel: DesignableLabel!
    @IBOutlet weak var coinPriceValueLabel: UILabel!
    @IBOutlet weak var dateTimeStockValueSegment: UISegmentedControl!

    @IBOutlet weak var BuyAmountTextField: UITextField!
    @IBOutlet weak var BuyButton: DesignableButton!
    @IBOutlet weak var ChartViewContainer: DesignableView!
    
    weak var axisFormatDelegate: IAxisValueFormatter?
    var chartView: CandleChart!
    
    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        
        presenter.getCoinInfos()
        let ohlcvFromDate = getOhlcvDateFromSegment()
        presenter.getCoinOhlcv(from: ohlcvFromDate)
        
        dateTimeStockValueSegment.addTarget(self, action: #selector(BuyCoinsViewController.segmentedControlValueChanged(_:)), for: .valueChanged)
        
        initChartView()
        initBuyAmountPad()
        
    }
    
    func initBuyAmountPad() {
        let toolbar: UIToolbar = UIToolbar()
        
        toolbar.frame = CGRect(x: 0, y: 0, width: view.bounds.width, height: 44)
        toolbar.isTranslucent = false
        toolbar.barTintColor = .gray
        toolbar.tintColor = .white
        toolbar.items = [
            UIBarButtonItem(title: "Done", style: .done, target: self, action: #selector(doneButtonTappedForMyNumericTextField))
        ]
        toolbar.isTranslucent = true
        BuyAmountTextField.autoresizingMask = .flexibleHeight
        BuyAmountTextField.inputAccessoryView = toolbar
    }
    
    @objc func doneButtonTappedForMyNumericTextField() {
        print("Done");
        BuyAmountTextField.resignFirstResponder()
    }
    
    func initChartView() {
        let frame = CGRect(x: 10, y: 60, width: ChartViewContainer.frame.width - 30, height: ChartViewContainer.frame.height - 70)

        chartView = CandleChart(frame: frame)
        ChartViewContainer.addSubview(chartView)

        axisFormatDelegate = chartView
    }
    
    func getOhlcvDateFromSegment() -> Date {
        var date: Date = Date(timeIntervalSince1970: 0)
        
        switch dateTimeStockValueSegment.selectedSegmentIndex {
        case 0:
            date = (Calendar.current.date(byAdding: .hour, value: -1, to: Date())!)
        case 1:
            date = (Calendar.current.date(byAdding: .day, value: -1, to: Date()) ?? Date())
        case 2:
            date = (Calendar.current.date(byAdding: .weekday, value: -1, to: Date()) ?? Date())
        case 3:
            date = (Calendar.current.date(byAdding: .month, value: -1, to: Date()) ?? Date())
        default:
            break
        }
                
        return date
    }
    
    @objc func segmentedControlValueChanged(_ sender:UISegmentedControl!) {
        
        let ohlcvFromDate = getOhlcvDateFromSegment()
        presenter.getCoinOhlcv(from: ohlcvFromDate)

        switch dateTimeStockValueSegment.selectedSegmentIndex {
        case 0:
            chartView.selectedDate = .minute
        case 1:
            chartView.selectedDate = .hour
        case 2:
            chartView.selectedDate = .day
        case 3:
            chartView.selectedDate = .month
        case 4:
            chartView.selectedDate = .all
        default:
            chartView.selectedDate = .all
        }
            
    }
    
    @IBAction func BuyClick(_ sender: Any) {
        presenter.buyCoin(usdAmount: BuyAmountTextField.text)
    }
    
}

// MARK: - Extensions -

extension BuyCoinsViewController: BuyCoinsViewInterface {
    
    func didBoughtCoin(success: Bool) {
        if success {
            Toast.show(message: "Transaction done", controller: self, type: "success", toastDuration: 2)
        } else {
            Toast.show(message: "An error occured", controller: self, type: "danger", toastDuration: 2)
        }
    }

    func updateCoinView(coinInfos: Ticker) {
        let floatPrice = Float(truncating: coinInfos[.usd].price as NSNumber)

        coinPriceTitleLabel.text = Bundle.main.localizedString(forKey: "priceOf", value: "Price of", table: "Localizable") + " " + coinInfos.name
        coinPriceValueLabel.text = String(format: "%.2f", floatPrice) + " $"
    }
    
    func updateCoinView(coinOhlcv: [Ohlcv]) {
        chartView.updateDataView(coinOhlcv: coinOhlcv, axisFormatDelegate: axisFormatDelegate!)
    }
    
}

