//
//  HomeInterfaces.swift
//  IOS-Investment-App
//
//  Created by enki corbin on 01/12/2020.
//  Copyright (c) 2020 enki corbin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

class HomeTabBarController: UITabBarController {
    
    var presenter: HomePresenterInterface!
    
    private let _storyboard = UIStoryboard(name: "Main", bundle: nil)
    
    override func viewDidLoad() {

    }
    
    override func viewWillAppear(_ animated: Bool) {
        
        self.navigationController?.setCustomViewAppearance()

        self.viewControllers = presenter.getTabBarControllers()
        super.viewWillAppear(true)
    }
    

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    /*
     // MARK: - Navigation
     
     // In a storyboard-based application, you will often want to do a little preparation before navigation
     override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
     // Get the new view controller using segue.destinationViewController.
     // Pass the selected object to the new view controller.
     }
     */
    
}

extension HomeTabBarController: UITabBarControllerDelegate {
        
    func tabBarController(_ tabBarController: UITabBarController, didSelect viewController: UIViewController) {
        print("Selected \(viewController.title!)")
    }
    
}

// MARK: - Extensions -

extension HomeTabBarController: HomeViewInterface {


}
