//
//  PortfolioPresenter.swift
//  IOS-Investment-App
//
//  Created by enki corbin on 01/12/2020.
//  Copyright (c) 2020 enki corbin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PortfolioPresenter {

    // MARK: - Private properties -

    private unowned let view: PortfolioViewInterface
    private let interactor: PortfolioInteractorInterface
    private let wireframe: PortfolioWireframeInterface

    // MARK: - Lifecycle -

    init(view: PortfolioViewInterface, interactor: PortfolioInteractorInterface, wireframe: PortfolioWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension PortfolioPresenter: PortfolioPresenterInterface {
}
