//
//  PortfolioViewController.swift
//  IOS-Investment-App
//
//  Created by enki corbin on 01/12/2020.
//  Copyright (c) 2020 enki corbin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PortfolioViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: PortfolioPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }

    override func viewWillAppear(_ animated: Bool) {
        print("showing portfolio")
    }

}

// MARK: - Extensions -

extension PortfolioViewController: PortfolioViewInterface {
}
