//
//  PortfolioInterfaces.swift
//  IOS-Investment-App
//
//  Created by enki corbin on 01/12/2020.
//  Copyright (c) 2020 enki corbin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol PortfolioWireframeInterface: WireframeInterface {
}

protocol PortfolioViewInterface: ViewInterface {
}

protocol PortfolioPresenterInterface: PresenterInterface {
}

protocol PortfolioInteractorInterface: InteractorInterface {
    
}
